FROM ubuntu AS base

RUN apt-get update -y
RUN apt-get install -y python3 python3-dev python3-pip

RUN pip3 install --upgrade pip

RUN ln -s /usr/bin/python3 /usr/bin/python

FROM base AS bazel

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  build-essential openjdk-8-jdk zip unzip wget

WORKDIR /root

RUN wget https://github.com/bazelbuild/bazel/releases/download/0.19.1/bazel-0.19.1-dist.zip
RUN mkdir bazel-0.19.1
RUN unzip bazel-0.19.1-dist.zip -d bazel-0.19.1

WORKDIR /root/bazel-0.19.1

RUN bash ./compile.sh

FROM base AS tf

RUN pip3 install six numpy wheel mock
RUN pip3 install keras_applications==1.0.6 --no-deps
RUN pip3 install keras_preprocessing==1.0.5 --no-deps

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  build-essential openjdk-8-jdk unzip wget

WORKDIR /root

COPY --from=bazel /root/bazel-0.19.1/output/bazel /usr/local/bin/bazel

RUN wget https://github.com/tensorflow/tensorflow/archive/v1.12.0.zip

RUN unzip v1.12.0.zip -d ./

WORKDIR /root/tensorflow-1.12.0


