#
# Create multiarch python container
#

FROM multiarch/ubuntu-core:arm64-bionic as base

RUN apt-get update -y
RUN apt-get install -y python3 python3-dev python3-pip

RUN pip3 install --upgrade pip

FROM seankelly/multiarch-bld:arm64-latest as bazel

FROM base as tf

COPY --from=bazel /root/bazel-0.21.0/output/bazel /usr/local/bin/bazel

RUN pip3 install six numpy wheel mock
RUN pip3 install keras_applications==1.0.6 --no-deps
RUN pip3 install keras_preprocessing==1.0.5 --no-deps

