#
# Create multiarch python container
#

FROM multiarch/ubuntu-core:arm64-bionic

# uwsgi-plugin-python3 python-setuptools

RUN apt-get update -y \
	&& apt-get install -y python3 python3-dev python3-pip nginx \
	&& pip3 install uwsgi

COPY requirements.txt /requirements.txt

RUN pip3 install -r requirements.txt

EXPOSE 80

COPY nginx.conf /etc/nginx/sites-enabled/default

COPY start.sh /start.sh
RUN chmod +x /start.sh

COPY app app/

ENV PYTHONPATH=/app
WORKDIR /app

CMD ["/start.sh"]
